name: Build-Deploy-Test-Future-Branch
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Git SHA to Deploy'
      skipPipelineTrigger:
        description: Skip pipeline trigger
        type: boolean
        required: false
        default: false

jobs:
  build:
    if: ${{ github.event.inputs.skipPipelineTrigger == 'false' }}
    name: Build and Deploy
    runs-on: eg-default
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          overwrite-settings: false

      - name: Add CA certs to java keystore
        uses: eg-cicd/setup-java-cert@v1
