name: 'Dependency Review'
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Git SHA to Deploy'
      skipPipelineTrigger:
        description: Skip pipeline trigger
        type: boolean
        required: false
        default: false
jobs:
  build:
    if: ${{ github.event.inputs.skipPipelineTrigger == 'false' }}
    name: Build and Deploy
    runs-on: echo ${{ github.event.inputs.sha }}
